import { createLightTheme, type BrandVariants, type Theme } from '@fluentui/react-components'
import { innoTokens } from './tokens.js'

const brand: BrandVariants = {
  10: '#0a0a0a',
  20: '#141414',
  30: '#1d1d1d',
  40: '#262626',
  50: '#303030',
  60: '#3a3a3a',
  70: '#454545',
  80: innoTokens.accent,
  90: '#525252',
  100: '#6e6e6e',
  110: '#8a8a8a',
  120: '#a6a6a6',
  130: '#c2c2c2',
  140: '#dedede',
  150: '#ececec',
  160: '#f5f5f5',
}

const base = createLightTheme(brand)

export const innoTheme: Theme = {
  ...base,
  colorBrandBackground: innoTokens.accent,
  colorBrandBackgroundHover: innoTokens.accentHover,
  colorBrandBackgroundPressed: innoTokens.accentHover,
  colorBrandForeground1: '#FFFFFF',
  colorBrandForeground2: '#FFFFFF',
  colorNeutralBackground1: innoTokens.canvas,
  colorNeutralBackground2: innoTokens.canvasAlt,
  colorNeutralBackground3: innoTokens.canvasMuted,
  colorNeutralForeground1: innoTokens.textPrimary,
  colorNeutralForeground2: innoTokens.textSecondary,
  colorNeutralForeground3: innoTokens.textTertiary,
  colorNeutralStroke1: innoTokens.separatorStrong,
  colorNeutralStroke2: innoTokens.separator,
  borderRadiusSmall: innoTokens.radiusSm,
  borderRadiusMedium: innoTokens.radiusMd,
  borderRadiusLarge: innoTokens.radiusLg,
  fontFamilyBase: '-apple-system, BlinkMacSystemFont, "Segoe UI Variable", "Segoe UI", sans-serif',
  spacingVerticalS: '8px',
  spacingVerticalM: '12px',
  spacingVerticalL: '16px',
  spacingHorizontalM: '12px',
  spacingHorizontalL: '16px',
  shadow2: 'none',
  shadow4: 'none',
  shadow8: 'none',
  shadow16: 'none',
  shadow28: 'none',
  shadow64: 'none',
}
