import { createLightTheme, type BrandVariants, type Theme } from '@fluentui/react-components'
import { opptrixTokens } from './tokens.js'

const brand: BrandVariants = {
  10: '#0a0a0a',
  20: '#141414',
  30: '#1d1d1d',
  40: '#262626',
  50: '#303030',
  60: '#3a3a3a',
  70: '#454545',
  80: opptrixTokens.accent,
  90: '#525252',
  100: '#6e6e6e',
  110: '#8a8a8a',
  120: '#a6a6a6',
  130: '#c2c2c2',
  140: '#dedede',
  150: '#ececec',
  160: '#f5f5f5',
}

const base = createLightTheme(brand)

export const opptrixTheme: Theme = {
  ...base,
  colorBrandBackground: opptrixTokens.accent,
  colorBrandBackgroundHover: opptrixTokens.accentHover,
  colorBrandBackgroundPressed: opptrixTokens.accentHover,
  colorBrandForeground1: '#FFFFFF',
  colorBrandForeground2: '#FFFFFF',
  colorNeutralBackground1: opptrixTokens.canvas,
  colorNeutralBackground2: opptrixTokens.canvasAlt,
  colorNeutralBackground3: opptrixTokens.canvasMuted,
  colorNeutralForeground1: opptrixTokens.textPrimary,
  colorNeutralForeground2: opptrixTokens.textSecondary,
  colorNeutralForeground3: opptrixTokens.textTertiary,
  colorNeutralStroke1: opptrixTokens.separatorStrong,
  colorNeutralStroke2: opptrixTokens.separator,
  borderRadiusSmall: opptrixTokens.radiusSm,
  borderRadiusMedium: opptrixTokens.radiusMd,
  borderRadiusLarge: opptrixTokens.radiusLg,
  fontFamilyBase: '-apple-system, BlinkMacSystemFont, "Segoe UI Variable", "Segoe UI", sans-serif',
  spacingVerticalS: '8px',
  spacingVerticalM: '12px',
  spacingVerticalL: '16px',
  spacingHorizontalM: '12px',
  spacingHorizontalL: '16px',
  shadow2: 'none',
  shadow4: 'none',
  shadow8: 'none',
  shadow16: 'none',
  shadow28: 'none',
  shadow64: 'none',
}
