/** aaashare Capability enum — data dimension identifiers */
export enum Capability {
  STOCK_REALTIME = 'stock_realtime',
  STOCK_KLINE = 'stock_kline',
  STOCK_MONEY_FLOW = 'stock_money_flow',
  INDEX_REALTIME = 'index_realtime',
  INDEX_KLINE = 'index_kline',
  MARKET_MONEY_FLOW = 'market_money_flow',
  SECTOR_MONEY_FLOW = 'sector_money_flow',
  SECTOR_LIST = 'sector_list',
  STOCK_BASIC = 'stock_basic',
  STOCK_PROFILE = 'stock_profile',
  SHAREHOLDER = 'shareholder',
  FINANCIAL_SUMMARY = 'financial_summary',
  NEWS = 'news',
  SENTIMENT = 'sentiment',
  DRAGON_TIGER = 'dragon_tiger',
  MARGIN_TRADE = 'margin_trade',
  DIVIDEND = 'dividend',
  BALANCE_SHEET = 'balance_sheet',
  INCOME_STMT = 'income_statement',
  CASH_FLOW = 'cash_flow',
  INST_HOLDING = 'inst_holding',
  BLOCK_TRADE = 'block_trade',
  LOCKUP_EXPIRY = 'lockup_expiry',
  SHARE_PLEDGE = 'share_pledge',
  INTRADAY_TICK = 'intraday_tick',
  STOCK_LIST = 'stock_list',
  INDEX_CONST = 'index_constituent',
  INSIDER_TRADE = 'insider_trade',
  PERF_FORECAST = 'performance_forecast',
  TRADE_CALENDAR = 'trade_calendar',
  LIMIT_UPDOWN = 'limit_updown',
  MARKET_BREADTH = 'market_breadth',
  IPO_DATA = 'ipo_data',
  CONVERTIBLE_BOND = 'convertible_bond',
  ETF_DATA = 'etf_data',
  ETF_LIST = 'etf_list',
  ETF_PROFILE = 'etf_profile',
  ETF_HOLDINGS = 'etf_holdings',
  ETF_NAV = 'etf_nav',
  MANAGER_INFO = 'manager_info',
  SHAREHOLDER_PLAN = 'shareholder_plan',
  BUYBACK = 'buyback',
  GLOBAL_INDEX = 'global_index',
  EXCHANGE_RATE = 'exchange_rate',
  MACRO_INDICATOR = 'macro_indicator',
  TECH_INDICATOR = 'tech_indicator',
  MAIN_BUSINESS = 'main_business',
  TOP_CUSTOMER = 'top_customer',
  ACTUAL_CONTROLLER = 'actual_controller',
  SUBSIDIARY = 'subsidiary',
  RELATED_PARTY = 'related_party',
  RD_INVESTMENT = 'rd_investment',
  MERGER_ACQUISITION = 'merger_acquisition',
  EMPLOYEE_COMP = 'employee_composition',
  INSTITUTIONAL_VISIT = 'institutional_visit',
  PEER_COMPANY = 'peer_company',
  CHIP_DISTRIBUTION = 'chip_distribution',
}

/** Maps capability → cache type key (mirrors Python CACHE_TYPE) */
export const CACHE_TYPE: Partial<Record<Capability, string>> = {
  [Capability.STOCK_REALTIME]: 'stock_realtime',
  [Capability.STOCK_KLINE]: 'stock_kline',
  [Capability.STOCK_MONEY_FLOW]: 'stock_money_flow',
  [Capability.INDEX_REALTIME]: 'index_realtime',
  [Capability.INDEX_KLINE]: 'index_kline',
  [Capability.MARKET_MONEY_FLOW]: 'market_money_flow',
  [Capability.SECTOR_MONEY_FLOW]: 'sector_money_flow',
  [Capability.STOCK_PROFILE]: 'stock_profile',
  [Capability.FINANCIAL_SUMMARY]: 'financial_summary',
  [Capability.BALANCE_SHEET]: 'balance_sheet',
  [Capability.INCOME_STMT]: 'income_statement',
  [Capability.CASH_FLOW]: 'cash_flow',
  [Capability.SHAREHOLDER]: 'shareholder',
  [Capability.DIVIDEND]: 'dividend',
  [Capability.NEWS]: 'news',
  [Capability.SENTIMENT]: 'sentiment',
  [Capability.STOCK_LIST]: 'stock_list',
  [Capability.ETF_PROFILE]: 'etf_profile',
  [Capability.ETF_NAV]: 'etf_nav',
  [Capability.ETF_HOLDINGS]: 'etf_holdings',
}
