import type { CustomMethodApiDoc } from '../common/custom-method-doc-types.js'
import { toCustomMethodDef } from '../common/custom-method-doc-types.js'

const PROXY = 'https://proxy.finance.qq.com'
const MSTATS = 'https://stockapp.finance.qq.com/mstats'

const INVOKE = (method: string, args = '["300308"]') =>
  `engine.invokeCustomMethod("tencent", "${method}", ${args})`

export const TENCENT_METHOD_DOCS: Record<string, CustomMethodApiDoc> = {
  tencentGlobalFuturesList: {
    method: 'tencentGlobalFuturesList',
    description: '全球期货实时列表（能源/贵金属/农产品/利率/汇率/股指期货等）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/app/rank/worldCommodities`,
    pageUrl: `${MSTATS}/#mod=list&id=qh_global&module=GQH&type=ALL`,
    params: [
      { name: 'category', type: 'string', description: '品类：ALL、energy、preciousMetal、agriculture、basicMetal、exchangeRate、interestRate、stockIndex；支持中文别名如「能源」', default: 'ALL' },
      { name: 'page', type: 'number', description: '页码，从 1 开始（客户端分页）', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 200', default: 40 },
      { name: 'sortType', type: 'string', description: '排序：0 名称 / 1 最新价 / 2 涨跌额 / 3 涨跌幅，或字段名 zxj/zde/zdf', default: 1 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ category, page, pageSize, total, items: [{ code, qtCode, name, price, changeAmt, changePct, exchange, tradeStateLabel, categoryLabel, ... }], source }]',
    usage: INVOKE('tencentGlobalFuturesList', '["ALL",1,40,3,"desc"]'),
    notes: '上游一次返回全部分类；筛选/排序/分页在本地完成。报价延迟约 15 分钟（与 mstats 页一致）。',
    example: '{"provider":"tencent","method":"tencentGlobalFuturesList","args":["ALL",1,40,3,"desc"]}',
  },

  tencentGlobalIndexList: {
    method: 'tencentGlobalIndexList',
    description: '全球股指列表（亚/欧/美/其他分区或 ALL 去重合并）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/app/rank/indexRankDetail2`,
    pageUrl: `${MSTATS}/#mod=list&id=indices&module=GIDX&type=ALL`,
    params: [
      { name: 'region', type: 'string', description: '分区：ALL、EU、europe、AM、america、AS、asia、OA、other', default: 'ALL' },
      { name: 'page', type: 'number', description: '页码（客户端分页）', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数', default: 40 },
      { name: 'sortType', type: 'string', description: '0 名称 / 1 最新价 / 2 涨跌幅', default: 1 },
      { name: 'order', type: 'string', description: 'desc|down 或 asc|up', default: 'desc' },
    ],
    returns: '[{ region, page, pageSize, total, items: [{ code, qtCode, name, price, changePct, location, tradeStateLabel, region, market }], source }]',
    usage: INVOKE('tencentGlobalIndexList', '["ALL",1,40,2,"desc"]'),
    notes: 'ALL 合并 common/america/europe/asia/other 并按 qtcode 去重。延迟约 15 分钟。',
    example: '{"provider":"tencent","method":"tencentGlobalIndexList","args":["EU",1,20,2,"desc"]}',
  },

  tencentCnIndexSnapshot: {
    method: 'tencentCnIndexSnapshot',
    description: 'A 股主要指数 / mstats 首页滚动指数快照（qt.gtimg.cn 批量行情）',
    sourceUrl: 'https://qt.gtimg.cn/q=sh000001,sz399001,sz399006,...',
    pageUrl: `${MSTATS}/#`,
    params: [
      { name: 'preset', type: 'string', description: 'major（默认 7 只 A 股主要指数）/ mstats_home（首页滚动条 12 只）/ custom（配合 codes）', default: 'major' },
      { name: 'includeBoardRanks', type: 'boolean', description: '是否附带上证/深证指数成分涨跌榜（bkqtRank_A_sh/sz）', default: false },
      { name: 'codes', type: 'string', description: '可选，逗号分隔 qt 代码覆盖 preset，如 sh000001,sz399300', default: '' },
      { name: 'boardRankPageSize', type: 'number', description: '指数成分榜条数，最大 50', default: 10 },
    ],
    returns: '[{ preset, symbols, items: [{ code, qtCode, name, price, changePct, changeAmt, open, high, low, volume, amount, quoteTime, market }], boardRanks?: { shanghai, shenzhen }, source }]',
    usage: INVOKE('tencentCnIndexSnapshot', '["major",false]'),
    notes: '与 tencentGlobalIndexList（indexRankDetail2 全球股指）不同；本接口为实时 qt 文本行情，含 A 股/港股/美股/期货首页条。成分榜仅交易时段有数据。',
    example: '{"provider":"tencent","method":"tencentCnIndexSnapshot","args":["mstats_home",false]}',
  },

  tencentHsjStockList: {
    method: 'tencentHsjStockList',
    description: '沪深京 A 股排行列表（mstats hs_hsj，含行情摘要，服务端分页）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/rank/hs/getBoardRankList?board_code=aStock&sort_type=priceRatio&direct=down&offset=0&count=20`,
    pageUrl: `${MSTATS}/#mod=list&id=hs_hsj&module=hs&type=hsj`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅，或 price/priceRatio/volume 等', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "aStock", boardKey, boardLabel, mstatsListId: "hs_hsj", page, pageSize, total, items: [{ code, name, price, changePct, volume, peTtm, marketCap, ... }], source }]',
    usage: INVOKE('tencentHsjStockList', '[1,20,32,"desc"]'),
    notes: '等价于 tencentCnStockList("hsj", ...)；上游 board_code=aStock，全市场约 5500+ 只。优于标准 stockList("hsj") 仅返回前 100 条且无行情字段。',
    example: '{"provider":"tencent","method":"tencentHsjStockList","args":[1,20,32,"desc"]}',
  },

  tencentCybStockList: {
    method: 'tencentCybStockList',
    description: '创业板股票列表（mstats hs_cyb，含行情摘要，服务端分页）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/rank/hs/getBoardRankList?board_code=cyb`,
    pageUrl: `${MSTATS}/#mod=list&id=hs_cyb&module=hs&type=cyb`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅，或 price/priceRatio/volume 等', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "cyb", mstatsListId: "hs_cyb", page, pageSize, total, items, source }]',
    usage: INVOKE('tencentCybStockList', '[1,20,32,"desc"]'),
    notes: '等价于 tencentCnStockList("cyb", ...)；上游 board_code=cyb。',
    example: '{"provider":"tencent","method":"tencentCybStockList","args":[1,20,32,"desc"]}',
  },

  tencentKcbStockList: {
    method: 'tencentKcbStockList',
    description: '科创板股票列表（mstats hs_kcb，含行情摘要，服务端分页）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/rank/hs/getBoardRankList?board_code=ksh`,
    pageUrl: `${MSTATS}/#mod=list&id=hs_kcb&module=hs&type=kcb`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅，或 price/priceRatio/volume 等', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "ksh", mstatsListId: "hs_kcb", page, pageSize, total, items, source }]',
    usage: INVOKE('tencentKcbStockList', '[1,20,32,"desc"]'),
    notes: '等价于 tencentCnStockList("kcb", ...)；上游 board_code=ksh（mstats type=kcb）。',
    example: '{"provider":"tencent","method":"tencentKcbStockList","args":[1,20,32,"desc"]}',
  },

  tencentCnStockList: {
    method: 'tencentCnStockList',
    description: '沪深 A 股板块排行（通用：hsj / cyb / kcb）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/rank/hs/getBoardRankList`,
    pageUrl: `${MSTATS}/#mod=list&id=hs_hsj&module=hs&type=hsj`,
    params: [
      { name: 'board', type: 'string', description: 'hsj（沪深京）/ cyb（创业板）/ kcb（科创板）', default: 'hsj' },
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号或 sort_type 字段名', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board, boardKey, boardLabel, mstatsListId, page, pageSize, total, items, source }]',
    usage: INVOKE('tencentCnStockList', '["hsj",1,20,32,"desc"]'),
    example: '{"provider":"tencent","method":"tencentCnStockList","args":["cyb",1,20,3,"desc"]}',
  },

  tencentHkStockList: {
    method: 'tencentHkStockList',
    description: '港股排行列表（mstats HK：主板/创业板/恒指成分等）',
    sourceUrl: 'https://stock.gtimg.cn/data/hk_rank.php?board=main_all&metric=change_rate&pageSize=20&reqPage=1&order=0&var_name=list_data',
    pageUrl: `${MSTATS}/#mod=list&id=hk_mb&module=hk&type=MB`,
    params: [
      { name: 'board', type: 'string', description: 'mstats type：MB（主板）、GEM（创业板）、HSI、HSCEI、AH 等；或直接传 main_all/gem_all', default: 'MB' },
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅，或 price/change_rate/volume 等', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board, boardKey, boardLabel, page, pageSize, total, items: [{ code, name, price, changePct, changeAmt, buy, sell, volume, amount, market }], source }]',
    usage: INVOKE('tencentHkStockList', '["MB",1,20,32,"desc"]'),
    notes: '优先 hk_rank.php JSONP；盘前或非交易时段可能返回空，自动回退 proxy rank/hk/getList（board_type）。港股代码 5 位如 00700。',
    example: '{"provider":"tencent","method":"tencentHkStockList","args":["GEM",1,20,32,"desc"]}',
  },

  tencentHkMainBoardStockList: {
    method: 'tencentHkMainBoardStockList',
    description: '港股主板股票列表（mstats hk_mb，含行情摘要，服务端分页）',
    sourceUrl: 'https://stock.gtimg.cn/data/hk_rank.php?board=main_all&metric=price&pageSize=20&reqPage=1&order=0&var_name=list_data',
    pageUrl: `${MSTATS}/#mod=list&id=hk_mb&module=HK&type=MB&sort=3&page=1&max=20`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始（对应 mstats page）', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100（对应 mstats max）', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价（mstats 默认）/ 32 涨跌幅，或 price/change_rate', default: 3 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "main_all", boardKey: "MB", boardLabel: "港股主板", page, pageSize, total, items: [{ code, name, price, changePct, changeAmt, preClose, open, high, low, buy, sell, volume, amount, market }], source }]',
    usage: INVOKE('tencentHkMainBoardStockList', '[1,20,3,"desc"]'),
    notes: '等价于 tencentHkStockList("MB", ...)；默认 sort=3 与 mstats 主板页一致。共约 1000+ 只，按 stock_count 分页。',
    example: '{"provider":"tencent","method":"tencentHkMainBoardStockList","args":[1,20,3,"desc"]}',
  },

  tencentHkAhStockList: {
    method: 'tencentHkAhStockList',
    description: 'A+H 股列表（港股侧 AH 溢价排行，含行情摘要，服务端分页）',
    sourceUrl: 'https://stock.gtimg.cn/data/hk_rank.php?board=A_H&metric=change_rate&pageSize=20&reqPage=1&order=0&var_name=list_data',
    pageUrl: `${MSTATS}/#mod=list&id=hk_ah&module=HK&type=AH`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅（默认）/ 36 成交量，或 price/change_rate', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "A_H", boardKey: "AH", boardLabel: "AH股", page, pageSize, total, items: [{ code, name, price, changePct, changeAmt, preClose, open, high, low, buy, sell, volume, amount, market }], source }]',
    usage: INVOKE('tencentHkAhStockList', '[1,20,32,"desc"]'),
    notes: '等价于 tencentHkStockList("AH", ...)；上游 board=A_H。列表含 AH 溢价率等字段（page_data 末位）。',
    example: '{"provider":"tencent","method":"tencentHkAhStockList","args":[1,20,32,"desc"]}',
  },

  tencentHkMbHsceiStockList: {
    method: 'tencentHkMbHsceiStockList',
    description: '港股主板国企股列表（含行情摘要，服务端分页）',
    sourceUrl: 'https://stock.gtimg.cn/data/hk_rank.php?board=main_China&metric=change_rate&pageSize=20&reqPage=1&order=0&var_name=list_data',
    pageUrl: `${MSTATS}/#mod=list&id=hk_mb_hscei&module=HK&type=MBHSCEI`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅（默认），或 price/change_rate', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "main_China", boardKey: "MBHSCEI", boardLabel: "主板国企股", page, pageSize, total, items, source }]',
    usage: INVOKE('tencentHkMbHsceiStockList', '[1,20,32,"desc"]'),
    notes: '等价于 tencentHkStockList("MBHSCEI", ...)；上游 board=main_China。',
    example: '{"provider":"tencent","method":"tencentHkMbHsceiStockList","args":[1,20,32,"desc"]}',
  },

  tencentHkMbHscciStockList: {
    method: 'tencentHkMbHscciStockList',
    description: '港股主板红筹股列表（含行情摘要，服务端分页）',
    sourceUrl: 'https://stock.gtimg.cn/data/hk_rank.php?board=main_red&metric=change_rate&pageSize=20&reqPage=1&order=0&var_name=list_data',
    pageUrl: `${MSTATS}/#mod=list&id=hk_mb_hscci&module=HK&type=MBHSCCI`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅（默认），或 price/change_rate', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "main_red", boardKey: "MBHSCCI", boardLabel: "主板红筹", page, pageSize, total, items, source }]',
    usage: INVOKE('tencentHkMbHscciStockList', '[1,20,32,"desc"]'),
    notes: '等价于 tencentHkStockList("MBHSCCI", ...)；上游 board=main_red。',
    example: '{"provider":"tencent","method":"tencentHkMbHscciStockList","args":[1,20,32,"desc"]}',
  },

  tencentHkBullWarrantList: {
    method: 'tencentHkBullWarrantList',
    description: '港股牛证列表（含行情摘要，服务端分页）',
    sourceUrl: 'https://stock.gtimg.cn/data/hk_rank.php?board=niuxiong_niu&metric=change_rate&pageSize=20&reqPage=1&order=0&var_name=list_data',
    pageUrl: `${MSTATS}/#mod=list&id=hk_cbbc_pull&module=HK&type=BULL`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅（默认），或 price/change_rate', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "niuxiong_niu", boardKey: "BULL", boardLabel: "牛证", page, pageSize, total, items, source }]',
    usage: INVOKE('tencentHkBullWarrantList', '[1,20,32,"desc"]'),
    notes: '等价于 tencentHkStockList("BULL", ...)；上游 board=niuxiong_niu。牛熊证代码常为 5 位数字。',
    example: '{"provider":"tencent","method":"tencentHkBullWarrantList","args":[1,20,32,"desc"]}',
  },

  tencentHkBearWarrantList: {
    method: 'tencentHkBearWarrantList',
    description: '港股熊证列表（含行情摘要，服务端分页）',
    sourceUrl: 'https://stock.gtimg.cn/data/hk_rank.php?board=niuxiong_xiong&metric=change_rate&pageSize=20&reqPage=1&order=0&var_name=list_data',
    pageUrl: `${MSTATS}/#mod=list&id=hk_cbbc_bear&module=HK&type=BEAR`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅（默认），或 price/change_rate', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "niuxiong_xiong", boardKey: "BEAR", boardLabel: "熊证", page, pageSize, total, items, source }]',
    usage: INVOKE('tencentHkBearWarrantList', '[1,20,32,"desc"]'),
    notes: '等价于 tencentHkStockList("BEAR", ...)；上游 board=niuxiong_xiong。',
    example: '{"provider":"tencent","method":"tencentHkBearWarrantList","args":[1,20,32,"desc"]}',
  },

  tencentUsTechStockList: {
    method: 'tencentUsTechStockList',
    description: '美股科技股排行列表（含最新价、涨跌幅、市值、市盈率等行情摘要）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/rank/us/getList?board_type=tec&sort_type=priceRatio&direct=down&offset=0&count=20`,
    pageUrl: `${MSTATS}/#mod=list&id=us_kjg&module=US&type=tec`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始（服务端分页）', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅 / 36 成交量 / 4 总市值，或 price/priceRatio/volume/marketValue', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "tec", boardLabel, page, pageSize, total, items: [{ code, symbol, name, price, changePct, changeAmt, turnoverRate, amplitude, volume, turnover, peTtm, pb, marketCap, floatMarketCap, market }], source }]',
    usage: INVOKE('tencentUsTechStockList', '[1,20,32,"desc"]'),
    notes: '上游 board_type=tec；symbol 为 usTICKER.EX 格式，code 为纯 ticker。延迟约 15 分钟。',
    example: '{"provider":"tencent","method":"tencentUsTechStockList","args":[1,20,32,"desc"]}',
  },

  tencentUsChinaAdrList: {
    method: 'tencentUsChinaAdrList',
    description: '中概股排行列表（含最新价、涨跌幅、市值、市盈率等行情摘要）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/rank/us/getList?board_type=cdr&sort_type=priceRatio&direct=down&offset=0&count=20`,
    pageUrl: `${MSTATS}/#mod=list&id=us_zgg&module=US&type=cdr`,
    params: [
      { name: 'page', type: 'number', description: '页码，从 1 开始（服务端分页）', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: '列序号 3 最新价 / 32 涨跌幅 / 36 成交量 / 4 总市值，或 price/priceRatio/volume/marketValue', default: 32 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ board: "cdr", boardLabel: "中概股", page, pageSize, total, items: [{ code, symbol, name, price, changePct, changeAmt, turnoverRate, amplitude, volume, turnover, peTtm, pb, marketCap, floatMarketCap, market }], source }]',
    usage: INVOKE('tencentUsChinaAdrList', '[1,20,32,"desc"]'),
    notes: '上游 board_type=cdr（mstats type=cdr / id=us_zgg）。与科技股共用 rank/us/getList。',
    example: '{"provider":"tencent","method":"tencentUsChinaAdrList","args":[2,20,32,"desc"]}',
  },

  tencentIndustryHeatRank: {
    method: 'tencentIndustryHeatRank',
    description: 'mstats 首页行业热度排行（板块平均涨跌幅 + 领涨股）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/app/mktHs/rank?l=10&p=1&t=averatio&o=0`,
    pageUrl: `${MSTATS}/#`,
    params: [
      { name: 'type', type: 'string', description: 'averatio（行业平均涨跌幅）或 01/averatio（沪深 A 股行业平均，首页市场一览）', default: 'averatio' },
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 50', default: 10 },
      { name: 'order', type: 'string', description: 'desc/down → 涨幅榜（o=0）；asc/up → 跌幅榜（o=1）', default: 'desc' },
    ],
    returns: '[{ type, page, pageSize, order, total, items: [{ industryCode, industryName, changePct, changePct5d, changePct20d, leadingStock: { code, name, changePct }, ... }], source }]',
    usage: INVOKE('tencentIndustryHeatRank', '["averatio",1,10,"desc"]'),
    notes: 't=01 单独使用会 TYPE_ERROR；请用 averatio 或 01/averatio。',
    example: '{"provider":"tencent","method":"tencentIndustryHeatRank","args":["01/averatio",1,10,"desc"]}',
  },

  tencentExchangeRateList: {
    method: 'tencentExchangeRateList',
    description: '全球外汇汇率列表（mstats ER：基本汇率 + 交叉汇率）',
    sourceUrl: 'https://qt.gtimg.cn/?q=whUSDCNY,whEURUSD,...',
    pageUrl: `${MSTATS}/#mod=list&id=exchange&module=ER&type=ALL`,
    params: [
      { name: 'category', type: 'string', description: 'ALL、BASE（基本汇率）、CROSS（交叉汇率）；支持中文「基本汇率」', default: 'ALL' },
      { name: 'page', type: 'number', description: '页码，从 1 开始（客户端分页）', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 200', default: 40 },
      { name: 'sortType', type: 'string', description: '0 名称 / 1 货币对 / 2 最新价 / 3 涨跌幅 / 4 涨跌额', default: 3 },
      { name: 'order', type: 'string', description: 'desc|down 降序，asc|up 升序', default: 'desc' },
    ],
    returns: '[{ category, page, pageSize, total, items: [{ code, qtCode, name, price, changeAmt, changePct, preClose, open, high, low, bid, ask, quoteTime, categoryLabel, market }], source }]',
    usage: INVOKE('tencentExchangeRateList', '["ALL",1,40,3,"desc"]'),
    notes: '数据源为 qt.gtimg.cn wh* 代码（与 mstats listTPL.ER 一致）；非 worldCommodities 的 exchangeRate 期货桶。Capability exchangeRate(pair) 亦走此接口。',
    example: '{"provider":"tencent","method":"tencentExchangeRateList","args":["BASE",1,20,3,"desc"]}',
  },

  tencentShenwanIndustryList: {
    method: 'tencentShenwanIndustryList',
    description: '申万行业板块列表（一级/二级，含阶段涨跌幅与领涨股）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/rank/pt/getRank?board_type=hy|hy2&sort_type=...&offset=...&count=...`,
    pageUrl: `${MSTATS}/#mod=list&id=hy_first&module=hy&type=first`,
    params: [
      { name: 'level', type: 'string', description: 'first（申万一级，board_type=hy）或 second（二级，hy2）', default: 'first' },
      { name: 'page', type: 'number', description: '页码', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 100', default: 20 },
      { name: 'sortType', type: 'string', description: 'sort_type 或列序号：2 最新价、3 涨跌幅、priceRatioD5 等', default: 'priceRatio' },
      { name: 'order', type: 'string', description: 'desc/down 或 asc/up → direct=down|up', default: 'desc' },
    ],
    returns: '[{ level, page, pageSize, total, items: [{ industryCode, name, price, changePct, changePct5d/20d/60d/52w/ytd, leadingStock, level, ... }], source }]',
    usage: INVOKE('tencentShenwanIndustryList', '["first",1,20,"priceRatio","desc"]'),
    notes: '一级约 31 条、二级约 124 条。行业代码格式 pt01801780，用于成分股接口。',
    example: '{"provider":"tencent","method":"tencentShenwanIndustryList","args":["first",2,20,3,"desc"]}',
  },

  tencentIndustryConstituents: {
    method: 'tencentIndustryConstituents',
    description: '申万行业成分股排行（点击行业进入的个股列表）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/rank/hs/getBoardRankList?board_code={industryCode}&_appver=11.17.0&...`,
    pageUrl: `${MSTATS}/#mod=list&id=pt01801780&typename=银行&sign=web`,
    params: [
      { name: 'industryCode', type: 'string', description: '行业板块代码，来自 tencentShenwanIndustryList 的 industryCode', required: true },
      { name: 'page', type: 'number', description: '页码', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数', default: 20 },
      { name: 'sortType', type: 'string', description: 'sort_type 或列序号，默认 priceRatio（涨跌幅）', default: 'priceRatio' },
      { name: 'order', type: 'string', description: 'desc/down 或 asc/up', default: 'desc' },
    ],
    returns: '[{ industryCode, page, pageSize, total, items: [{ code, name, price, changePct, peTtm, volume, turnover, ... }], source }]',
    usage: INVOKE('tencentIndustryConstituents', '["pt01801780",1,20,"priceRatio","desc"]'),
    notes: 'board_code 为行业 pt 代码，非股票代码。与沪深板块排行共用 getBoardRankList。',
    example: '{"provider":"tencent","method":"tencentIndustryConstituents","args":["pt01801780",1,20,"priceRatio","desc"]}',
  },

  tencentStockPlates: {
    method: 'tencentStockPlates',
    description: '个股行业/概念/地域标签',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/app/stockinfo/plateNew?code={symbol}&app=wzq&zdf=1`,
    pageUrl: 'https://gu.qq.com/{symbol}/gp',
    params: [{ name: 'code', type: 'string', description: '6 位 A 股代码', required: true }],
    returns: '[{ code, plateType: industry|concept|area, plateName, changePct, tag, source }]',
    usage: INVOKE('tencentStockPlates'),
    notes: 'symbol 自动补 sh/sz 前缀。',
    example: '{"provider":"tencent","method":"tencentStockPlates","args":["300308"]}',
  },

  tencentRelatedPlates: {
    method: 'tencentRelatedPlates',
    description: '个股关联板块列表',
    sourceUrl: `${PROXY}/ifzqgtimg/stock/relate/data/plate?code={symbol}`,
    pageUrl: 'https://gu.qq.com/{symbol}/gp',
    params: [{ name: 'code', type: 'string', description: '6 位 A 股代码', required: true }],
    returns: '[{ code, peerCode, peerName, source }]',
    usage: INVOKE('tencentRelatedPlates'),
    example: '{"provider":"tencent","method":"tencentRelatedPlates","args":["600519"]}',
  },

  tencentIndustryRank: {
    method: 'tencentIndustryRank',
    description: '个股在所属行业内的估值排名（PE/市值/每股收益）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/hs/hypm/get?code={symbol}`,
    pageUrl: 'https://gu.qq.com/{symbol}/gp',
    params: [{ name: 'code', type: 'string', description: '6 位 A 股代码', required: true }],
    returns: '[{ code, industryCode, industryName, pe, marketCap, eps, peRank, marketCapRank, epsRank, industryAvgPe, source }]',
    usage: INVOKE('tencentIndustryRank'),
    notes: '与 tencentShenwanIndustryList（全市场行业榜）不同，此为单股行业内排名。',
    example: '{"provider":"tencent","method":"tencentIndustryRank","args":["300308"]}',
  },

  tencentInstitutionRating: {
    method: 'tencentInstitutionRating',
    description: '机构评级汇总、近期研报标题与目标价区间',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/app/investRate/getInvestRate + /ifzqgtimg/appstock/hs/jggd/get`,
    pageUrl: 'https://gu.qq.com/{symbol}/gp/yjbg',
    params: [{ name: 'code', type: 'string', description: '6 位 A 股代码', required: true }],
    returns: '[{ code, ratings, recentReports, monthly: { m1,m2,m3 }, targetPrice: { avg,high,low }, source }]',
    usage: INVOKE('tencentInstitutionRating'),
    example: '{"provider":"tencent","method":"tencentInstitutionRating","args":["600519"]}',
  },

  tencentStockSearch: {
    method: 'tencentStockSearch',
    description: '股票/基金搜索（smartbox）',
    sourceUrl: `${PROXY}/cgi/cgi-bin/smartbox/search?stockFlag=1&fundFlag=1&query={q}`,
    pageUrl: `${MSTATS}/`,
    params: [{ name: 'query', type: 'string', description: '代码或名称关键词', required: true }],
    returns: 'TencentSmartboxStock[] 原始搜索结果',
    usage: INVOKE('tencentStockSearch', '["茅台"]'),
    example: '{"provider":"tencent","method":"tencentStockSearch","args":["300308"]}',
  },

  tencentTradeDetails: {
    method: 'tencentTradeDetails',
    description: '逐笔成交明细（盘中有效）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/app/dealinfo/getMingxiV2?code={symbol}`,
    pageUrl: 'https://gu.qq.com/{symbol}/gp',
    params: [{ name: 'code', type: 'string', description: '6 位 A 股代码', required: true }],
    returns: '[{ code, time, price, volume, side, ... }]',
    usage: INVOKE('tencentTradeDetails'),
    notes: '收盘后常返回空；仅交易时段有逐笔数据。',
    example: '{"provider":"tencent","method":"tencentTradeDetails","args":["300308"]}',
  },

  tencentHkStockProfile: {
    method: 'tencentHkStockProfile',
    description: '港股基本资料（公司名称、官网、主营业务）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/app/hkStockinfo/jiankuang?code=hk00700`,
    pageUrl: 'https://gu.qq.com/hk00700/gp',
    params: [{ name: 'code', type: 'string', description: '港股代码，如 00700 或 hk00700', required: true }],
    returns: '[{ code, symbol, chiName, website, business, raw, source }]',
    usage: INVOKE('tencentHkStockProfile', '["00700"]'),
    notes: '与 A 股 stockinfo/jiankuang 不同，须走 hkStockinfo 路径。',
    example: '{"provider":"tencent","method":"tencentHkStockProfile","args":["00700"]}',
  },

  tencentHkStockNews: {
    method: 'tencentHkStockNews',
    description: '港股个股新闻列表（详情页侧边栏）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/news/info/search?symbol=hk00700&type=2`,
    pageUrl: 'https://gu.qq.com/hk00700/gp',
    params: [
      { name: 'code', type: 'string', description: '港股代码', required: true },
      { name: 'page', type: 'number', description: '页码', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 50', default: 20 },
    ],
    returns: '[{ code, total, items: [{ id, title, time, url, type }], source }]',
    usage: INVOKE('tencentHkStockNews', '["00700",1,10]'),
    notes: 'type=2 为个股新闻；type=1 常为空。与 A 股 HyNews/getBySymbol 不通用。',
    example: '{"provider":"tencent","method":"tencentHkStockNews","args":["00700",1,10]}',
  },

  tencentHkStockNotices: {
    method: 'tencentHkStockNotices',
    description: '港股个股公告列表',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/news/noticeList/search?symbol=hk00700`,
    pageUrl: 'https://gu.qq.com/hk00700/gp',
    params: [
      { name: 'code', type: 'string', description: '港股代码', required: true },
      { name: 'page', type: 'number', description: '页码', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 50', default: 20 },
    ],
    returns: '[{ code, total, items: [{ id, title, time, url, type }], source }]',
    usage: INVOKE('tencentHkStockNotices', '["00700",1,10]'),
    example: '{"provider":"tencent","method":"tencentHkStockNotices","args":["00700",1,10]}',
  },

  tencentHkStockFinancialReport: {
    method: 'tencentHkStockFinancialReport',
    description: '港股财务三表（损益表 / 现金流量表 / 资产负债表）',
    sourceUrl: `${PROXY}/ifzqgtimg/stock/corp/hkcwbb/detail?type=zhsy|xjll|zcfz&symbol=hk00700`,
    pageUrl: 'https://gu.qq.com/hk00700/gp/income',
    params: [
      { name: 'code', type: 'string', description: '港股代码', required: true },
      { name: 'reportType', type: 'string', description: 'income 损益 / cashflow 现金流 / balance 负债', default: 'income' },
      { name: 'reportPeriod', type: 'string', description: 'all 全部 / annual 年报 / interim 中报', default: 'all' },
      { name: 'periods', type: 'number', description: '返回期数，最大 12', default: 4 },
    ],
    returns: '[{ code, reportType, reportPeriod, tables, source }]',
    usage: INVOKE('tencentHkStockFinancialReport', '["00700","income","all",4]'),
    notes: '上游 getFinReport 已 offline；须用 hkcwbb/detail。type 映射：zhsy/xjll/zcfz。',
    example: '{"provider":"tencent","method":"tencentHkStockFinancialReport","args":["00700","balance"]}',
  },

  tencentHkStockKline: {
    method: 'tencentHkStockKline',
    description: '港股 K 线（分时 / 五日 / 日周月 / 1-3-5 年，支持历史区间）',
    sourceUrl: 'https://web.ifzq.gtimg.cn/appstock/app/minute/query | day/query | kline/kline',
    pageUrl: 'https://gu.qq.com/hk00700/gp',
    params: [
      { name: 'code', type: 'string', description: '港股代码', required: true },
      { name: 'period', type: 'string', description: 'minute|fdays|day|week|month|year1|year3|year5', default: 'day' },
      { name: 'limit', type: 'number', description: 'K 线条数，0 表示默认；上游单次最大 2000', default: 0 },
      { name: 'adjust', type: 'string', description: 'none 不复权 / qfq 前复权（仅日周月年）', default: 'none' },
      { name: 'startDate', type: 'string', description: '历史起始 YYYY-MM-DD；与 endDate 配合可拉全量历史', default: '' },
      { name: 'endDate', type: 'string', description: '历史截止 YYYY-MM-DD；省略时默认今天', default: '' },
    ],
    returns: '[{ code, symbol, period, adjust, startDate, endDate, items, quote?, source }]',
    usage: INVOKE('tencentHkStockKline', '["00700","day",0,"none","2004-01-01","2026-07-08"]'),
    notes: '日 K 历史超过约 4 年或 limit≥2000 时自动按年分批请求并合并（与 gu.qq.com 图表一致）。周/月单次即可覆盖全历史。分时仅当日，五日固定近 5 个交易日。',
    example: '{"provider":"tencent","method":"tencentHkStockKline","args":["00700","day",0,"none","2004-01-01"]}',
  },

  tencentHkTechnicalAnalysis: {
    method: 'tencentHkTechnicalAnalysis',
    description: '港股技术面（最活跃成交价位分布 + 均价波幅）',
    sourceUrl: `${PROXY}/message/hk/hk_trading_vol_analyse.php?code=00700 + Hkinchot/averageVolatility`,
    pageUrl: 'https://gu.qq.com/hk00700/gp',
    params: [{ name: 'code', type: 'string', description: '港股代码', required: true }],
    returns: '[{ code, symbol, trading: { priceLevels, largeOrderPct }, average: { ma10..ma250, volatility }, source }]',
    usage: INVOKE('tencentHkTechnicalAnalysis', '["00700"]'),
    notes: '成交分布用 5 位代码（无 hk 前缀）；均价波幅盘前可能为 NA。',
    example: '{"provider":"tencent","method":"tencentHkTechnicalAnalysis","args":["00700"]}',
  },

  tencentHkRelatedStocks: {
    method: 'tencentHkRelatedStocks',
    description: '港股关联股票列表',
    sourceUrl: `${PROXY}/ifzqgtimg/hk/aastocks/relate/relate?code=hk00700`,
    pageUrl: 'https://gu.qq.com/hk00700/gp',
    params: [{ name: 'code', type: 'string', description: '港股代码', required: true }],
    returns: '[{ code, items: [{ code, name }], source }]',
    usage: INVOKE('tencentHkRelatedStocks', '["00700"]'),
    example: '{"provider":"tencent","method":"tencentHkRelatedStocks","args":["00700"]}',
  },

  tencentHkReviewProspect: {
    method: 'tencentHkReviewProspect',
    description: '港股业绩回顾与业务展望（HTML 正文）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/hk/HkInfo/getReview?c=00700 + getProspect`,
    pageUrl: 'https://gu.qq.com/hk00700/gp',
    params: [{ name: 'code', type: 'string', description: '港股代码', required: true }],
    returns: '[{ code, review, prospect, source }]',
    usage: INVOKE('tencentHkReviewProspect', '["00700"]'),
    notes: '参数为 c=5位代码，非 hk 前缀。',
    example: '{"provider":"tencent","method":"tencentHkReviewProspect","args":["00700"]}',
  },

  tencentHkInvestRating: {
    method: 'tencentHkInvestRating',
    description: '港股投行评级与目标价',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/hk/HkInfo/getInvestBankRating?c=00700`,
    pageUrl: 'https://gu.qq.com/hk00700/gp',
    params: [{ name: 'code', type: 'string', description: '港股代码', required: true }],
    returns: '[{ code, items: [{ DEPARTMENT_NAME, AIM_PRICE, EVA_RANK, ... }], source }]',
    usage: INVOKE('tencentHkInvestRating', '["00700"]'),
    example: '{"provider":"tencent","method":"tencentHkInvestRating","args":["00700"]}',
  },

  tencentHkDividends: {
    method: 'tencentHkDividends',
    description: '港股分红派息（详情页底部摘要 + 完整分页列表）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/hk/HkInfo/getDividends?c=00700&p=1&max=10 + jiankuang.fhpx`,
    pageUrl: 'https://gu.qq.com/hk00700/gp/dividends',
    params: [
      { name: 'code', type: 'string', description: '港股代码', required: true },
      { name: 'page', type: 'number', description: '页码，从 1 开始', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 50（对应上游 max）', default: 10 },
      { name: 'includeRecent', type: 'boolean', description: '是否附带 jiankuang.fhpx 近年摘要（详情页底部）', default: true },
    ],
    returns: '[{ code, symbol, page, pageSize, hasMore, recent: [{ content, exDate, payDate }], items: [{ fiscalYear, eventType, method, exDate, payDate, content, ... }], source }]',
    usage: INVOKE('tencentHkDividends', '["00700",1,5]'),
    notes: 'recent 来自 jiankuang.fhpx，含 2024-2026 等最新派息；items 来自 getDividends 历史档案（腾讯控股约至 2018）。参数 c=5 位代码。',
    example: '{"provider":"tencent","method":"tencentHkDividends","args":["00700",1,10,true]}',
  },

  tencentUsStockProfile: {
    method: 'tencentUsStockProfile',
    description: '美股基本资料（公司名称、上市日期、行业、营收构成）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/us/introduce/brief?symbol=usEQIX.OQ&app=official_website`,
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg/jbzl',
    params: [{ name: 'code', type: 'string', description: '美股代码，如 EQIX、usEQIX.OQ', required: true }],
    returns: '[{ code, symbol, companyName, listingDate, exchange, website, industry, description, totalShares, revenueBreakdown, raw, source }]',
    usage: INVOKE('tencentUsStockProfile', '["usEQIX.OQ"]'),
    notes: 'symbol 自动规范为 us{TICKER}.{OQ|N|AM}；未带后缀时默认 .OQ。',
    example: '{"provider":"tencent","method":"tencentUsStockProfile","args":["EQIX"]}',
  },

  tencentUsStockQuote: {
    method: 'tencentUsStockQuote',
    description: '美股实时行情（价格、涨跌、成交、估值、52周高低）',
    sourceUrl: 'https://qt.gtimg.cn/q=usEQIX',
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg',
    params: [{ name: 'code', type: 'string', description: '美股代码', required: true }],
    returns: '[{ code, symbol, qtCode, name, price, preClose, open, high, low, changeAmt, changePct, volume, amount, pe, pb, marketCap, currency, quoteTime, week52High, week52Low, source }]',
    usage: INVOKE('tencentUsStockQuote', '["NVDA"]'),
    notes: 'qt 查询码为 us{TICKER}（无 .OQ 后缀）；附 mobile/qt/data 增强 52 周高低与估值。',
    example: '{"provider":"tencent","method":"tencentUsStockQuote","args":["usNVDA.OQ"]}',
  },

  tencentUsStockNews: {
    method: 'tencentUsStockNews',
    description: '美股个股新闻列表（详情页侧边栏）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/news/info/search?symbol=usEQIX.OQ&type=2`,
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg/news',
    params: [
      { name: 'code', type: 'string', description: '美股代码', required: true },
      { name: 'page', type: 'number', description: '页码', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 51', default: 20 },
    ],
    returns: '[{ code, total, totalPages, page, pageSize, items: [{ id, title, time, url, type }], source }]',
    usage: INVOKE('tencentUsStockNews', '["EQIX",1,10]'),
    notes: '上游 total_page 约 2000；type=2 为个股新闻。',
    example: '{"provider":"tencent","method":"tencentUsStockNews","args":["usEQIX.OQ",1,5]}',
  },

  tencentUsStockNotices: {
    method: 'tencentUsStockNotices',
    description: '美股公司公告列表',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/news/noticeList/search?symbol=usEQIX.OQ`,
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg/gsgg',
    params: [
      { name: 'code', type: 'string', description: '美股代码', required: true },
      { name: 'page', type: 'number', description: '页码', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 50', default: 20 },
    ],
    returns: '[{ code, total, page, pageSize, items: [{ id, title, time, url, type }], source }]',
    usage: INVOKE('tencentUsStockNotices', '["EQIX",1,10]'),
    notes: '部分美股标的公告源为空（如 EQIX 返回 0 条）。',
    example: '{"provider":"tencent","method":"tencentUsStockNotices","args":["usEQIX.OQ",1,10]}',
  },

  tencentUsFinancialSummary: {
    method: 'tencentUsFinancialSummary',
    description: '美股财务摘要（按年：营收/净利润、总资产/负债、现金流）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/us/UsCw/cwData?symbol=usEQIX.OQ&page=1&num=10`,
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg/cwsj',
    params: [
      { name: 'code', type: 'string', description: '美股代码', required: true },
      { name: 'page', type: 'number', description: '页码（每页约 10 个财年）', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 20', default: 10 },
    ],
    returns: '[{ code, page, pageSize, items: [{ year, income, balance, cash }], source }]',
    usage: INVOKE('tencentUsFinancialSummary', '["NVDA",1,10]'),
    notes: '侧栏摘要与 cwsj 页均走 UsCw/cwData；finDetail/search 对美股已不可用。',
    example: '{"provider":"tencent","method":"tencentUsFinancialSummary","args":["usEQIX.OQ",1,4]}',
  },

  tencentUsShareholderStats: {
    method: 'tencentUsShareholderStats',
    description: '美股股东统计（标普机构持仓）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/app/StandardPoorsGudong/holdingOwnerList?code=usEQIX.OQ`,
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg',
    params: [
      { name: 'code', type: 'string', description: '美股代码', required: true },
      { name: 'page', type: 'number', description: '页码（上游目前固定返回约 50 条）', default: 1 },
    ],
    returns: '[{ code, asOfDate, page, items: [{ name, shares, shareRatio, sharesChange, ratioChange, period, holderType }], source }]',
    usage: INVOKE('tencentUsShareholderStats', '["EQIX"]'),
    notes: '参数名为 code（非 symbol）；page 暂不影响结果集。',
    example: '{"provider":"tencent","method":"tencentUsShareholderStats","args":["usEQIX.OQ"]}',
  },

  tencentUsSeniorTrades: {
    method: 'tencentUsSeniorTrades',
    description: '美股高管交易记录（内幕交易披露）',
    sourceUrl: `${PROXY}/ifzqgtimg/appstock/us/Manager/getTrade?symbol=usEQIX.OQ&page=1&num=10`,
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg',
    params: [
      { name: 'code', type: 'string', description: '美股代码', required: true },
      { name: 'page', type: 'number', description: '页码', default: 1 },
      { name: 'pageSize', type: 'number', description: '每页条数，最大 50', default: 10 },
    ],
    returns: '[{ code, page, pageSize, items: [{ ric, code, name, date, shares, value, detail }], source }]',
    usage: INVOKE('tencentUsSeniorTrades', '["EQIX",1,10]'),
    example: '{"provider":"tencent","method":"tencentUsSeniorTrades","args":["usEQIX.OQ",1,10]}',
  },

  tencentUsRelatedStocks: {
    method: 'tencentUsRelatedStocks',
    description: '美股关联股票列表（附简要行情）',
    sourceUrl: `${PROXY}/ifzqgtimg/stock/relate/data/usRelateStocks?code=usEQIX.OQ`,
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg',
    params: [{ name: 'code', type: 'string', description: '美股代码', required: true }],
    returns: '[{ code, items: [{ code, symbol, name, price, changePct }], source }]',
    usage: INVOKE('tencentUsRelatedStocks', '["EQIX"]'),
    notes: '参数名为 code；行情通过 qt.gtimg.cn 批量补充。',
    example: '{"provider":"tencent","method":"tencentUsRelatedStocks","args":["usEQIX.OQ"]}',
  },

  tencentUsStockKline: {
    method: 'tencentUsStockKline',
    description: '美股 K 线（分时 / 五日 / 日周月 / 1-3-5 年，支持历史区间）',
    sourceUrl: 'https://web.ifzq.gtimg.cn/appstock/app/minute/query | kline/kline | usfqkline/get',
    pageUrl: 'https://gu.qq.com/usEQIX.OQ/gg',
    params: [
      { name: 'code', type: 'string', description: '美股代码', required: true },
      { name: 'period', type: 'string', description: 'minute|fdays|day|week|month|year1|year3|year5', default: 'day' },
      { name: 'limit', type: 'number', description: 'K 线条数，0 表示默认；上游单次最大 2000', default: 0 },
      { name: 'adjust', type: 'string', description: 'none 不复权 / qfq 前复权（日周月年）', default: 'none' },
      { name: 'startDate', type: 'string', description: '历史起始 YYYY-MM-DD', default: '' },
      { name: 'endDate', type: 'string', description: '历史截止 YYYY-MM-DD', default: '' },
    ],
    returns: '[{ code, symbol, period, adjust, startDate, endDate, items, quote?, source }]',
    usage: INVOKE('tencentUsStockKline', '["NVDA","day",0,"none","2020-01-01","2026-07-08"]'),
    notes: 'symbol 为 us{TICKER}.OQ；前复权走 usfqkline/get。五日 fdays 为 m5 日 K 摘要（非港股式分时五日）。日 K 跨多年自动按年分批。',
    example: '{"provider":"tencent","method":"tencentUsStockKline","args":["usNVDA.OQ","week"]}',
  },

  // ===== ETF 基金专用方法 =====

  tencentFundProfile: {
    method: 'tencentFundProfile',
    description: 'ETF 基金概况（基金经理、管理人、托管人、净值、溢价率、规模、分红等）',
    sourceUrl: 'https://web.ifzq.gtimg.cn/fund/newfund/fundBase/getPriceZone?symbol={market}{code}',
    pageUrl: 'https://gu.qq.com/{market}{code}',
    params: [{ name: 'code', type: 'string', description: '6 位 ETF 代码（如 159971）', required: true }],
    returns: '{ code, data: { info: { jjdm, jjqc, jjjc, jjlx, jjjl, glrmc, tgrmc, dwjz, ljjz, zxgm, ... }, data: { zxjg, zyjl, jgzffd, ... }, profit: { ljfh, ljfhcs } } }',
    usage: INVOKE('tencentFundProfile', '["159971"]'),
    notes: 'JSONP 接口，info 含基金档案，data 含实时价格与溢价率，profit 含分红记录。',
    example: '{"provider":"tencent","method":"tencentFundProfile","args":["159971"]}',
  },

  tencentFundAsset: {
    method: 'tencentFundAsset',
    description: 'ETF 资产配置（股票/债券比例、行业分布、前十大持仓）',
    sourceUrl: 'https://zxg.txfund.com/ifzqgtimg/appstock/fund/baseInfo/asset?code={market}{code}',
    params: [{ name: 'code', type: 'string', description: '6 位 ETF 代码', required: true }],
    returns: '{ code, data: { selector: string[], report_time, total_money, asset: [{name,ratio}], industry: [{name,ratio}], stock: [{name,code,ratio,rate}] } }',
    usage: INVOKE('tencentFundAsset', '["159971"]'),
    notes: 'JSONP 接口。stock[] 为前十大持仓，industry[] 为行业分布，asset[] 为大类资产配置。',
    example: '{"provider":"tencent","method":"tencentFundAsset","args":["159971"]}',
  },

  tencentFundRankInfo: {
    method: 'tencentFundRankInfo',
    description: 'ETF 业绩排名（近1/4/13/26/52周/今年/成立以来净值增长率与同类平均）',
    sourceUrl: 'https://web.ifzq.gtimg.cn/fund/newfund/fundBase/getRankInfo?symbol={market}{code}',
    params: [{ name: 'code', type: 'string', description: '6 位 ETF 代码', required: true }],
    returns: '{ code, data: { zxrq, total, jzzf: {w1,w4,w13,w26,w52,year,total,year3}, avg_hbl: {...} } }',
    usage: INVOKE('tencentFundRankInfo', '["159971"]'),
    notes: 'JSONP 接口。jzzf 为净值增长率，avg_hbl 为同类平均回报率。',
    example: '{"provider":"tencent","method":"tencentFundRankInfo","args":["159971"]}',
  },

  tencentFundNavHistory: {
    method: 'tencentFundNavHistory',
    description: 'ETF 全量历史净值（从成立日至今的单位净值与累计净值）',
    sourceUrl: 'https://stockjs.finance.qq.com/fundUnitNavAll/data/year_all/{code}.js',
    params: [{ name: 'code', type: 'string', description: '6 位 ETF 代码', required: true }],
    returns: '{ code, data: [[date, nav, accNav], ...] }',
    usage: INVOKE('tencentFundNavHistory', '["159971"]'),
    notes: 'JS var 赋值格式，需提取 = 后 JSON。data 数组每项为 [日期YYYYMMDD, 单位净值, 累计净值]。',
    example: '{"provider":"tencent","method":"tencentFundNavHistory","args":["159971"]}',
  },

  tencentEtfKline: {
    method: 'tencentEtfKline',
    description: 'ETF K 线（日/周/月，走 proxy.finance.qq.com 专用接口）',
    sourceUrl: 'https://proxy.finance.qq.com/kline/app/get?code={market}{code}&period={period}',
    params: [
      { name: 'code', type: 'string', description: '6 位 ETF 代码', required: true },
      { name: 'period', type: 'string', description: 'day / week / month', default: 'day' },
      { name: 'limit', type: 'number', description: 'K 线条数，0 表示默认', default: 0 },
    ],
    returns: '{ stockCode, nodes: [{ date, open, last, high, low, volume, amount, exchange, dividend }] }',
    usage: INVOKE('tencentEtfKline', '["159971","day",100]'),
    notes: '与标准 kline 走 qt.gtimg.cn 不同，本接口走 proxy.finance.qq.com，返回含 exchange（换手率）、dividend（分红）等 ETF 专有字段。',
    example: '{"provider":"tencent","method":"tencentEtfKline","args":["159971","week"]}',
  },

  tencentFundNotice: {
    method: 'tencentFundNotice',
    description: 'ETF 基金公告列表',
    sourceUrl: 'https://web.ifzq.gtimg.cn/fund/newfund/fundNotice/getNotice?symbol={market}{code}&page={page}&limit={limit}',
    params: [
      { name: 'code', type: 'string', description: '6 位 ETF 代码', required: true },
      { name: 'page', type: 'number', description: '页码', default: 1 },
      { name: 'limit', type: 'number', description: '每页条数', default: 20 },
    ],
    returns: '{ code, data: { [code]: { total, data: [{ id, title, date }] } } }',
    usage: INVOKE('tencentFundNotice', '["159971",1,10]'),
    notes: 'JSONP 接口。返回基金公告列表，含标题和发布日期。',
    example: '{"provider":"tencent","method":"tencentFundNotice","args":["159971",1,10]}',
  },

  tencentSameTypeFunds: {
    method: 'tencentSameTypeFunds',
    description: '同类基金列表（ETF 详情页右侧边栏）',
    sourceUrl: 'https://web.ifzq.gtimg.cn/fund/newfund/fundBase/getSameLxFundList?type=1&symbol={market}{code}',
    params: [{ name: 'code', type: 'string', description: '6 位 ETF 代码', required: true }],
    returns: '{ code, data: { list: [{ jjdm, jzrq, dwjz, jzzf, jzze, jjjc, sclx }] } }',
    usage: INVOKE('tencentSameTypeFunds', '["159971"]'),
    notes: 'JSONP 接口。type=1 为同类基金对比。',
    example: '{"provider":"tencent","method":"tencentSameTypeFunds","args":["159971"]}',
  },

  tencentSameSeriesFunds: {
    method: 'tencentSameSeriesFunds',
    description: '同系基金列表（同一管理人旗下基金）',
    sourceUrl: 'https://web.ifzq.gtimg.cn/fund/newfund/fundBase/getSameLxFundList?type=2&symbol={market}{code}',
    params: [{ name: 'code', type: 'string', description: '6 位 ETF 代码', required: true }],
    returns: '{ code, data: { list: [{ jjdm, jzrq, dwjz, jzzf, jzze, jjjc, sclx, txjjlx }] } }',
    usage: INVOKE('tencentSameSeriesFunds', '["159971"]'),
    notes: 'JSONP 接口。type=2 为同系列基金（同一管理人旗下）。',
    example: '{"provider":"tencent","method":"tencentSameSeriesFunds","args":["159971"]}',
  },
}

export const TENCENT_CUSTOM = Object.values(TENCENT_METHOD_DOCS).map(toCustomMethodDef)
