export { AgentEngine, ChatCancelledError, type AgentSettings, type ChatResult, type SessionContextUsage } from './engine.js'
export {
  appendReasoningTimeline,
  appendReasoningSegment,
  beginReasoningSegment,
  formatReasoningSegmentLabel,
  joinReasoningSegments,
  normalizeReasoningSegments,
  resolveReasoningSegments,
  updateLastReasoningSegmentContent,
  REASONING_TIMELINE_SEP,
  type ReasoningSegment,
} from './reasoning-timeline.js'
export {
  type ChatProgressEvent,
  type ChatProgressOptions,
  type ChatToolStep,
  type ChatToolStepStatus,
  type ChatUserPromptPayload,
  formatToolLabel,
} from './chat-progress.js'
export {
  type UserPromptAnswer,
  type UserPromptOption,
  type UserPromptPayload,
  type UserPromptMode,
  UserPromptBridge,
  UserPromptCancelledError,
  createUserPromptId,
  normalizeUserPromptOptions,
  parseAskUserArgs,
} from './user-prompt.js'
export {
  SteerBridge,
  formatSteerUserMessage,
  isSerialTool,
  SERIAL_TOOL_NAMES,
  partitionToolCallsForExecution,
  fingerprintToolCall,
  checkSpinGuard,
  recordSpinOutcome,
  buildSpinGuardTurnTail,
  clearSpinGuardSession,
  resetSpinGuardForTests,
  SPIN_GUARD_LIMITS,
  SPIN_POLL_TOOLS,
  SPIN_WAKE_SUCCESS_PROGRESS_TOOLS,
  isSpinPollTool,
  isSpinWakeSuccessProgressTool,
  isInProgressJobStatus,
  isAgentCursorSmoothEnabled,
  resolveMaxSafetyRounds,
  resolveSoftRemindRound,
  resolveSafetyStopReply,
  isLastSafetyRound,
  isDoomLoopEnabled,
  SOFT_REMIND_TURN_TAIL,
  LAST_STEP_TURN_TAIL,
  DOOM_LOOP_REPEAT_THRESHOLD,
  SAFETY_STOP_REPLY_SMOOTH,
  SAFETY_STOP_REPLY_LEGACY,
  truncateToolOutputForModel,
  pruneToolOutputDir,
  resolveToolOutputDir,
  TOOL_OUTPUT_MAX_LINES,
  TOOL_OUTPUT_MAX_BYTES,
  noteDoomLoopFingerprint,
  clearDoomLoopSession,
  resetDoomLoopForTests,
  DOOM_LOOP_TURN_TAIL,
  updateResearchChecklist,
  buildChecklistTurnTail,
  clearResearchChecklistSession,
  resetResearchChecklistForTests,
  seedChecklistOnSkillActivate,
  getResearchChecklist,
  resolveEffectiveResearchTier,
  shouldEnterVerifyPhase,
  resolveGatherToolChoice,
  resolveVerifyToolChoice,
  VERIFY_TURN_TAIL,
  type ResearchChecklistItem,
  type ToolCallLike,
  type ToolExecutionBatch,
  type SpinGuardBlock,
  type TruncateToolOutputResult,
  type DoomLoopHit,
} from './loop/index.js'
export {
  UNATTENDED_ASK_USER_RESULT,
  UNATTENDED_BLOCKED_TOOL_NAMES,
  UNATTENDED_SECRET_RESULT,
  UNATTENDED_TURN_TAIL_NOTE,
  appendUnattendedTurnTail,
  filterOpenAiToolsForUnattended,
  filterToolNamesForUnattended,
  isUnattendedBlockedTool,
  pickUnattendedConfirmIds,
} from './unattended.js'
export {
  type AgentAppContext,
  type PublicAppSettings,
  createDefaultAppContext,
  getCurrentTime,
  getDataLayerPaths,
  getAgentSafeDataLayerSummary,
  buildAgentSafeProjectInfo,
  getSystemInfo,
  resolveProjectRoot,
} from './app-context.js'
export { DiscoverRunner, type DiscoverProgress, type DiscoverResult, type DiscoverPhase, type DiscoverFinalItem } from './discover.js'
export {
  DISCOVER_STRATEGIES,
  getDiscoverStrategy,
  listDiscoverStrategiesPublic,
  primaryDiscoverProfile,
  buildStrategyExecutionPrompt,
  strategyToPlan,
  type DiscoverStrategy,
  type DiscoverStrategyCategory,
  type DiscoverPlanMode,
} from './discover-strategies.js'
export { ToolRegistry, DISCOVER_MINING_TOOL_NAMES } from './tools.js'
export {
  CHAT_MCP_TOOL_NAMES,
  UNIFIED_INSTRUMENT_TOOL_NAMES,
} from './unified-mcp-tools.js'
export {
  DATA_LAYER_MINING_TOOL_NAMES,
  TOOL_META,
  formatToolDescription,
  resolveToolPackId,
  mcpToolCatalog,
} from './tool-meta.js'
export { createMcpServer, runMcpStdio } from './mcp/server.js'
export { McpToolBroker } from './mcp/broker.js'
export {
  AggregatingToolBroker,
  getExternalMcpRegistry,
  resetExternalMcpRegistry,
  ExternalMcpRegistry,
  ExternalMcpHealth,
} from './mcp/external/index.js'
export {
  ToolPackSessionStore,
  resolveActivePackIds,
  toolNamesForPacks,
  listToolPacksPayload,
  unloadedToolHint,
} from './mcp/tool-pack-session.js'
export {
  resolvePackIdsFromSkill,
  splitSkillDeclarationTokens,
  type SkillPackDeclaration,
} from './mcp/skill-required-packs.js'
export {
  resolveSeedPacks,
  ToolPackResolver,
  MAX_SEEDED_BUSINESS_PACKS,
} from './mcp/tool-pack-resolver.js'
export {
  resolveToolRoutePlan,
  buildRoundRoutePlaybook,
  orderToolsByPreference,
  resolveResearchTier,
  TOOL_CONFUSION_PAIRS,
  type ToolRoutePlan,
  type RouteConfidence,
} from './mcp/tool-route-plan.js'
export { SessionStore, setSessionPersistHooks, sessionToMeta, isWakeResumeDisplayMessage, isSidebarSession, type SessionMeta, type SessionRecord, type SessionKind, type DisplayMessage, type TurnOrigin, type SessionContextRef, type SessionForkContextRef, type SessionSelectionContextRef, type SessionArticleContextRef, type CreateSessionOptions, type SessionLlmParams, type ReasoningEffort, DEFAULT_SESSION_TEMPERATURE, DEFAULT_SESSION_MAX_TOKENS } from './sessions.js'
export {
  getExpertCatalogService,
  ExpertCatalogService,
  resetExpertCatalogServiceForTests,
} from './experts/catalog-service.js'
export {
  StaticHttpExpertProvider,
  DEFAULT_EXPERT_CATALOG_BASE_URL,
  resetStaticHttpExpertProviderForTests,
} from './experts/static-http-provider.js'
export {
  LocalJsonExpertProvider,
  resetBuiltinExpertCacheForTests,
  type RemoteExpertProvider,
} from './experts/local-json-provider.js'
export {
  assembleSystemPrompt,
  buildLayer0Baseline,
  buildRolePersona,
  sanitizeExpertPersona,
  resolveInitialRolePersona,
  DEFAULT_RESEARCHER_PERSONA,
} from './experts/prompt-assembler.js'
export { SessionArchiveFolderStore, DEFAULT_SESSION_ARCHIVE_FOLDERS, type SessionArchiveFolder } from './archive-folders.js'
export { ProviderRegistry, type ProviderProfile, type AvailableModel } from './llm/providers.js'
export {
  resolveModelContextTokens,
  resolveContextBudget,
  DEFAULT_CONTEXT_TOKENS,
  SOFT_USAGE_RATIO,
  HARD_USAGE_RATIO,
} from './llm/model-context.js'
export {
  resolveModelContextTokensAsync,
  lookupModelsDevContextLimit,
  getModelsDevCatalog,
  resolveModelsDevProviderMeta,
  resetModelsDevCacheForTests,
  resolveModelMediaCapabilitiesAsync,
  lookupModelsDevMediaEntry,
  defaultTextOnlyMediaCapabilities,
  type ModelsDevCatalog,
  type ModelsDevProviderEntry,
  type ModelsDevProviderMeta,
} from './llm/models-dev-context.js'
export {
  saveAttachment,
  saveCanvasAttachment,
  saveMindmapAttachment,
  saveWebAttachment,
  updateCanvasAttachment,
  updateMindmapAttachment,
  updateWebAttachment,
  readAttachmentText,
  readWebIndexHtml,
  readAttachmentMeta,
  readAttachmentBuffer,
  deleteAttachment,
  deleteSessionAttachments,
  pruneOrphanChatAttachments,
  resolveAttachmentFilePath,
  resolveSafeWebRelativePath,
  resolveWebAttachmentDir,
  validateAttachmentAgainstCapabilities,
  isAttachmentReferenced,
  summarizePinnedLimits,
  parseNonNegativeIntHeader,
  resolveUploadMime,
  schedulePdfExtract,
  scheduleMediaTranscriptExtract,
  runPdfExtract,
  waitForAttachmentExtractReady,
  waitForPdfExtractReady,
  applyAttachmentExtractMeta,
  writeLegacyExtractArtifacts,
  listSessionAttachmentMetas,
  readExtractChunks,
  readExtractMarkdown,
  isPdfTextExtractReady,
  isLibraryExtractReady,
  isTranscriptExtractReady,
  registerDocumentIngestHook,
  registerPdfIngestHook,
  registerMediaTranscriptHook,
  ARTIFACT_SOURCE_MAX_CHARS,
} from './chat-attachments.js'
export type {
  DocumentIngestHook,
  MediaTranscriptHook,
  WaitAttachmentExtractResult,
  WaitAttachmentExtractOptions,
  WaitPdfExtractResult,
  LegacyExtractPayload,
} from './chat-attachments.js'
export {
  type MediaKind,
  type ChatAttachmentMeta,
  type CanvasAttachmentMeta,
  type CanvasPageSpec,
  type MindmapAttachmentMeta,
  type WebAttachmentMeta,
  type AttachmentExtractMeta,
  type AttachmentExtractStatus,
  type AttachmentExtractPhase,
  type AttachmentLimits,
  type ModelMediaCapabilities,
  mimeToMediaKind,
  inferMimeFromFilename,
  resolveMediaMime,
  formatBytesShort,
  mediaKindLabel,
  isLibraryIngestKind,
  isTranscriptExtractKind,
  CANVAS_MIME,
  CANVAS_EXT,
  CANVAS_DATA_FILE,
  MINDMAP_MIME,
  MINDMAP_EXT,
  MINDMAP_DATA_FILE,
  WEB_MIME,
  WEB_EXT,
  WEB_DATA_FILE,
} from './media-types.js'
export {
  resolveWebVendorRoot,
  readWebVendorManifest,
  summarizeWebVendorLibs,
  resolveSafeVendorRelativePath,
  type WebVendorManifest,
  type WebVendorFileEntry,
} from './web-vendor.js'
export { resolveAttachmentLimits, LARGE_FILE_WARN_BYTES } from './attachment-limits.js'
export {
  extractPdfToMarkdown,
  formatDocumentCatalogLine,
  linesToMarkdownTable,
  extractTablesFromPageText,
} from './pdf-extract.js'
export type {
  PdfExtractResult,
  PdfExtractPage,
  PdfExtractChunk,
} from './pdf-extract.js'
export {
  buildUserContentParts,
  attachmentToContentPart,
  attachmentToContentParts,
  chatMessageContentToText,
  parseAssistantResponseContent,
  modelAcceptsImageInput,
  sanitizeContentPartsForModelMedia,
  sanitizeMessagesForModelMedia,
} from './content-parts.js'
export type { ContentPart, TextContentPart, ImageUrlContentPart, FileContentPart, InputAudioContentPart } from './llm/provider.js'
export {
  formatTokenCount,
  formatTurnUsageLabel,
} from './llm/format-token-count.js'
export {
  type TokenUsage,
  type TokenUsageDisplay,
  type CacheWarmth,
  emptyTokenUsage,
  mergeTokenUsage,
  parseOpenAiUsage,
  resolveCacheWarmth,
  promptCacheKeyForSession,
} from './llm/token-usage.js'

export {
  type ChatContextUsageSnapshot,
  type ChatTurnUsageSnapshot,
} from './chat-progress.js'
export {
  type SessionMemory,
  formatSessionMemoryForPrompt,
  emptySessionMemory,
  parseSessionMemoryFromModelText,
} from './context/session-memory.js'
export {
  applySessionPersistSoftCap,
  estimateSessionPersistBytes,
  SESSION_PERSIST_TURNS_TRIGGER,
  SESSION_PERSIST_JSON_BYTES_TRIGGER,
  SESSION_PERSIST_KEEP_RECENT_TURNS,
  type SoftCapResult,
} from './context/session-persist-soft-cap.js'
export {
  ensureContextBudget,
  buildBudgetForModel,
  assembleModelView,
  microcompactMessages,
  isContextOverflowError,
  CONTEXT_COMPACT_HINT,
  type CompactLevel,
  type CompactResult,
} from './context/compact.js'
export {
  type ContextProjection,
  coveredPrefixHash,
  projectionValid,
  modelVisibleFromProjection,
  installMicroProjection,
  installMemoryProjection,
} from './context/projection.js'
export {
  parseContextProjection,
  readContextProjectionFromDisk,
  writeContextProjectionToDisk,
  resolveContextProjectionPath,
  computeContextUsagePercent,
  hydrateContextProjection,
  contextProjectionToRef,
  isContextProjectionRef,
  isFullContextProjection,
  CONTEXT_PROJECTION_PATH_KEY,
  type ContextProjectionRef,
} from './context/session-projection-disk.js'
export { estimateTextTokens, estimateMessageTokens } from './context/token-estimate.js'
export {
  createProvider,
  isConfigured,
  fetchOpenAiModelList,
  joinOpenAiCompatibleUrl,
  EMPTY_REPLY_REASONING_HINT,
  LEGACY_DEFAULT_MAX_TOKENS,
  LEGACY_ORDINARY_OUTPUT_TOKENS,
  ORDINARY_OUTPUT_TOKENS,
  REASONING_OUTPUT_TOKENS,
  HIGH_REASONING_OUTPUT_TOKENS,
  OUTPUT_TOKENS_64K,
  OUTPUT_TOKENS_128K,
  OUTPUT_TOKENS_384K,
  MAX_OUTPUT_TOKENS_PRESETS,
  autoOutputBudget,
  looksLikeReasoningModel,
  resolveRequestMaxTokens,
  resolveBodyToolChoice,
  type LlmConfig,
  type LlmTurn,
  type LlmChatDelta,
  type LlmChatOpts,
  type LlmToolChoice,
} from './llm/provider.js'
export { initOutboundNetwork, type OutboundConnectFamily, type OutboundNetworkStatus } from './llm/outbound-network.js'
export {
  scheduleTurnWake,
  cancelTurnWake,
  clearSessionTurnWakes,
  listPendingTurnWakes,
  configureTurnWakeRuntime,
  setTurnWakeResumeHandler,
  onTurnWakeFired,
  clampWakeSeconds,
  clampSuggestedWakeSeconds,
  estimateEtaFromProgress,
  formatWakeMessage,
  TURN_WAKE_MIN_SECONDS,
  TURN_WAKE_MAX_SECONDS,
  TURN_WAKE_MAX_PER_SESSION,
  TURN_WAKE_BUSY_DEFER_SECONDS,
  resetTurnWakeForTests,
  listTurnWakeIdsForTests,
  type TurnWakeJob,
  type TurnWakeResumeHandler,
  type TurnWakeRuntime,
  type TurnWakeFiredListener,
  type PendingTurnWakeInfo,
} from './turn-wake.js'

export {
  JOB_WATCH_MAX_PER_SESSION,
  JOB_BUSY_DEFER_SECONDS,
  JOB_PROGRESS_THROTTLE_MS,
  JOB_IN_FLIGHT_STATES,
  JOB_TERMINAL_STATES,
  isJobWatchEnabled,
  jobRegistry,
  getJobRegistry,
  sessionResumeBus,
  getSessionResumeBus,
  formatJobResumeMessage,
  watchRegistry,
  getWatchRegistry,
  listPendingJobWatches,
  maybeAutoWatchFromToolResult,
  isAutoWatchEligible,
  buildDefaultResumePrompt,
  resolveJobKindFromTool,
  userFacingJobLabel,
  registerDefaultJobAdapters,
  unregisterJobAdaptersForTests,
  clearSessionJobWaitsAndWatches,
  resetJobsSubsystemForTests,
  type BackgroundJobKind,
  type BackgroundJobState,
  type BackgroundJobSnapshot,
  type ResumeRequest,
  type SessionResumeHandler,
  type JobWatch,
  type AttachWatchResult,
} from './jobs/index.js'

export {
  filterToolNamesForSubagent,
  filterToolsForSubagent,
  isSubagentBlockedTool,
  validateAgainstSchema,
  validateSubagentResult,
  resolveAuthSessionId,
  isSubagentSessionId,
  cascadeDeleteSubagents,
  cancelRunningSubagentsForParent,
  cancelSubagentRun,
  getSubagentRunRegistry,
  getSubagentRunResult,
  listSubagentRunsForParent,
  markRunNeedsParentAction,
  reclaimSubagentRun,
  resetSubagentRunRegistryForTests,
  SubagentRunRegistry,
  runSubagent,
  subagentBlockedToolError,
  type SubagentRun,
  type SubagentRole,
  type SubagentResultSchema,
  type SubagentToolResult,
  type SubagentRunStatus,
} from './subagents/index.js'

/** 注册 PDF → doc-library ingest hook */
import './doc-library-bridge.js'
